# Generated by Django 5.0.3 on 2024-03-30 04:24

import datetime
import django.db.models.deletion
import django.utils.timezone
import pizza.manage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_Menu',
            fields=[
                ('Pizza_menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pizza_Name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price', models.IntegerField()),
                ('Reg_serve_price', models.IntegerField()),
                ('med_serve_price', models.IntegerField()),
                ('lar_serve_price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza_type',
            fields=[
                ('Pizza_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('Pizza_type_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('contact', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=1)),
                ('otp', models.CharField(max_length=10)),
                ('otp_used', models.IntegerField(blank=True, null=True)),
                ('is_admin', models.IntegerField(blank=True, null=True)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_log_time', models.DateTimeField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('email_token', models.CharField(blank=True, max_length=100, null=True)),
                ('forget_password', models.CharField(blank=True, max_length=100, null=True)),
                ('old_cart', models.CharField(blank=True, max_length=200, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', pizza.manage.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=datetime.datetime.today)),
                ('delivery_address', models.CharField(max_length=50)),
                ('order_status', models.CharField(max_length=20)),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_mode', models.CharField(max_length=20)),
                ('delivery_status', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('Shipping_address', models.TextField(max_length=1500, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order_Items',
            fields=[
                ('order_de_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.order')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pizza_menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza_menu')),
            ],
        ),
        migrations.AddField(
            model_name='pizza_menu',
            name='Pizza_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.pizza_type'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_full_name', models.CharField(max_length=255)),
                ('shipping_email', models.CharField(max_length=255)),
                ('shipping_address1', models.CharField(max_length=255)),
                ('shipping_address2', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_state', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Address',
            },
        ),
    ]
