# Generated by Django 5.0.3 on 2024-04-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('rate', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
